inherit_from: ./.rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/**
    - .rubocop.yml

Style/Documentation:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 13
